### ISSUE TITLE
The --no-download and --no-upload options throw an error.

### ISSUE THREAD

**Issue by OzRocky** [Tux/speedtest#13]
Both no-download and no-upload commands return a valid result, but also throw the error shown below.

```
speedtest --no-upload
Testing for ###.###.###.### : Telstra Internet (AU)
Using  2582:   6.25 km     123 ms Australian Private Networks
Test download ........................................Download     34.713 Mbit/s

Argument "-" isn't numeric in addition (+) at C:\Strawberry\perl\site\bin/speedtest line 378.
```

Line 378 reads:
`push @try => [ $host, $dl, $ul, $dl + $ul ];`

If I edit the line and remove **$dl + $ul**, the error goes away. Who knows what else I just broke?

I'm running Strawberry Perl (64-bit) 5.30.0.1-64bit for Windows. Same results on Windows Server 2016 and Windows 7.

**Comment by Tux** [comment]
You did not break anything, and I never tested with these options obviously. It is a warning, as the report for upload or download when disabled is `-`, which is not a valid number
That is why the script issues a warning. I'll fix that
