### ISSUE TITLE
GEO-IP failed. Getting country code based on nearest server

### ISSUE THREAD

**Issue by bcooney** [Tux/speedtest#9]
While the speedtest worked, the GEO-IP failed, error above. Here it is in full:

    GEO-IP failed. Getting country code based on nearest server
    Testing for 117.184.89.114 : China Mobile (CN)
    Using 4665:  19.64 km      86 ms China Mobile Group Shanghai Co.,LTD
    Test download ........................................Download     54.511 Mbit/s
    Test upload   ........................................Upload       45.116 Mbit/s

Just FYI. Probably a China thing, honestly.

**Comment by Tux** [comment]
Noted. As it still works, this is just a warning to which I cannot add a "fix".
